/* Sync v3 — per-operation, per-field offline synchronisation. */
(function () {
  const config=globalThis.CAMP_SYNC_CONFIG, hasConfig=!!(config?.url&&config?.publishableKey);
  const clone=v=>v==null?v:structuredClone(v), same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
  const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
  const collections=['gear','recipes','trips','logs','discardedTrips','tripTombstones'];
  const entityId=(v,i)=>String(v?.id??v?.tripId??v?.code??`index:${i}`);
  const syncable=v=>{const n=clone(v||{});['page','pendingDeleteTripId','pendingPurgeId'].forEach(k=>delete n[k]);return n;};
  const cmp=(a,b)=>{if(!b)return 1;if(!a)return-1;for(const k of ['ms','counter']){const d=Number(a[k]||0)-Number(b[k]||0);if(d)return d;}return String(a.deviceId||'').localeCompare(String(b.deviceId||''));};
  const rowId=(field,v,i)=>field==='items'?String(v?.gearId??v?.id??`index:${i}`):String(v?.shoppingKey??v?.id??`${v?.recipeId||''}:${v?.name||''}:${i}`);
  const clockKey=(target,path)=>`${target}/${path.map(encodeURIComponent).join('/')}`;
  class CampSync {
    constructor(storage,key='camp-sync.v1'){this.storage=storage;this.key=key;this.deviceId=uid();this.timer=null;this.running=false;this.record={session:null,deviceId:this.deviceId,clock:{ms:0,counter:0},pending:[],known:[],snapshot:null,syncVersion:3};this.onStatus=()=>{};this.onQueue=()=>{};}
    async load(){const old=await this.storage.get(this.key)||{};this.record={...this.record,...old,syncVersion:3};this.deviceId=this.record.deviceId||this.deviceId;this.record.deviceId=this.deviceId;await this.persist();return this.record;}
    async persist(){await this.storage.set(this.key,this.record);} signedIn(){return!!this.record.session?.access_token;}
    headers(extra={}){const token=this.record.session?.access_token;return{apikey:config.publishableKey,Authorization:`Bearer ${token||config.publishableKey}`,'Content-Type':'application/json',...extra};}
    async request(path,options={}){const r=await fetch(`${config.url}${path}`,{...options,cache:'no-store',headers:this.headers(options.headers)});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.error_description||d.error||`同步服務錯誤 (${r.status})`);}return r.status===204?null:r.json();}
    async authRequest(path,options={}){const r=await fetch(`${config.url}${path}`,{...options,headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.error_description||d.error||`登入服務錯誤 (${r.status})`);}return r.status===204?null:r.json();}
    async signUp(email,password){const d=await this.authRequest('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});if(!d.session)throw new Error('帳號已建立；請先完成 Email 驗證。');this.record.session=d.session;await this.persist();return d;}
    async signIn(email,password){const d=await this.authRequest('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});this.record.session=d;await this.persist();return d;}
    async resendVerification(email){await this.authRequest('/auth/v1/resend',{method:'POST',body:JSON.stringify({type:'signup',email})});}
    async signOut(){await this.request('/auth/v1/logout',{method:'POST'}).catch(()=>{});this.record.session=null;await this.persist();}
    async refresh(){try{const t=this.record.session?.refresh_token;if(!t)return false;this.record.session=await this.authRequest('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:t})});await this.persist();return true;}catch{return false;}}
    needsRefresh(){return Number(this.record.session?.expires_at||0)<=Math.floor(Date.now()/1000)+60;}
    nextClock(){const old=this.record.clock||{},ms=Math.max(Date.now(),Number(old.ms||0)),counter=ms===Number(old.ms||0)?Number(old.counter||0)+1:0;return this.record.clock={ms,counter};}
    op(target,path,value,deleted=false){const c=this.nextClock();return{operationId:uid(),deviceId:this.deviceId,clock:{...c,deviceId:this.deviceId},occurredAt:new Date(c.ms).toISOString(),target,path,value:clone(value),deleted};}
    walk(before,after,target,path,ops){if(same(before,after))return;const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);if(obj(before)&&obj(after)){new Set([...Object.keys(before),...Object.keys(after)]).forEach(k=>this.walk(before[k],after[k],target,[...path,k],ops));}else ops.push(this.op(target,path,after,after===undefined));}
    entity(before,after,collection,itemId,ops){if(after===undefined){ops.push(this.op(`entity:${collection}:${itemId}`,[],null,true));return;}const old=before||{};if(collection==='trips'){for(const field of ['items','shopping']){const a=new Map((old[field]||[]).map((v,i)=>[rowId(field,v,i),v])),b=new Map((after[field]||[]).map((v,i)=>[rowId(field,v,i),v]));new Set([...a.keys(),...b.keys()]).forEach(k=>this.walk(a.get(k),b.get(k),`row:trips:${itemId}:${field}:${k}`,[],ops));}const a={...old},b={...after};delete a.items;delete a.shopping;this.walk(a,b,`entity:${collection}:${itemId}`,[],ops);return;}this.walk(old,after,`entity:${collection}:${itemId}`,[],ops);}
    build(before,after){if(before==null)return[this.op('snapshot',[],after)];const ops=[];for(const c of collections){const a=new Map((before[c]||[]).map((v,i)=>[entityId(v,i),v])),b=new Map((after[c]||[]).map((v,i)=>[entityId(v,i),v]));new Set([...a.keys(),...b.keys()]).forEach(k=>this.entity(a.get(k),b.get(k),c,k,ops));}const a=clone(before),b=clone(after);collections.forEach(k=>{delete a[k];delete b[k];});this.walk(a,b,'state',[],ops);return ops;}
    apply(bundle,op){const meta=bundle.meta||(bundle.meta={clocks:{},tombstones:{}}),data=bundle.data||(bundle.data={}),t=op.target,dead=meta.tombstones[t];if(op.deleted&&(!dead||cmp(op.clock,dead)>0))meta.tombstones[t]=op.clock;if(!op.deleted&&dead&&cmp(op.clock,dead)>0)delete meta.tombstones[t];if(!op.deleted&&meta.tombstones[t]&&cmp(op.clock,meta.tombstones[t])<=0)return;const ck=clockKey(t,op.path||[]);if(cmp(op.clock,meta.clocks[ck])<=0)return;meta.clocks[ck]=op.clock;if(t==='snapshot'){if(!bundle.seed||cmp(op.clock,bundle.seed)>0){bundle.data=clone(op.value||{});bundle.seed=op.clock;}return;}const parts=t.split(':');let root=data;if(parts[0]!=='state'){const[,c,parent,field,row]=parts;data[c]??=[];let e=data[c].find((v,i)=>entityId(v,i)===parent);if(!e&&!op.deleted){e={id:parent};data[c].push(e);}if(!e)return;if(field){e[field]??=[];let r=e[field].find((v,i)=>rowId(field,v,i)===row);if(!r&&!op.deleted){r=field==='items'?{gearId:row}:{shoppingKey:row};e[field].push(r);}root=r;}else root=e;if(op.deleted&&!(op.path||[]).length){const i=data[c].indexOf(e);if(i>=0)data[c].splice(i,1);return;}}if(!root)return;const p=op.path||[];if(!p.length){if(!op.deleted&&op.value&&typeof op.value==='object')Object.assign(root,clone(op.value));return;}let at=root;p.slice(0,-1).forEach(k=>at=at[k]??={});if(op.deleted)delete at[p[p.length-1]];else at[p[p.length-1]]=clone(op.value);}
    materialize(ops){const b={data:{},meta:{clocks:{},tombstones:{}}};[...ops].sort((a,b)=>cmp(a.clock,b.clock)||String(a.operationId).localeCompare(String(b.operationId))).forEach(op=>this.apply(b,op));return syncable(b.data);}
    stampChanges(){} queue(before,after){const next=syncable(after),prior=this.record.snapshot==null?syncable(before):this.record.snapshot,ops=this.build(prior,next);if(!ops.length)return;this.record.pending.push(...ops);this.record.snapshot=next;this.persist();this.onStatus('已離線儲存，等待同步');clearTimeout(this.timer);this.timer=setTimeout(()=>Promise.resolve(this.onQueue()).catch(()=>{}),100);}
    async exchange(ops,document){const rows=await this.request('/rest/v1/rpc/sync_camp_operations',{method:'POST',body:JSON.stringify({p_operations:ops,p_materialized:ops.length?document:null})});return Array.isArray(rows)?rows[0]:rows;}
    async sync(getState,replaceState){if(!hasConfig||!this.signedIn()||this.running||!navigator.onLine)return false;this.running=true;try{if(this.needsRefresh()&&!(await this.refresh()))throw new Error('登入已過期，請在設定重新登入');const local=syncable(getState()),pending=[...this.record.pending];let reply=await this.exchange(pending,local),remote=reply?.operations||[];if(!remote.length){const seedState=reply?.data&&Object.keys(reply.data).length?reply.data:local,seed=this.op('snapshot',[],seedState);reply=await this.exchange([seed,...pending],local);remote=reply?.operations||[];}const all=new Map([...this.record.known,...remote,...pending].map(x=>[x.operationId,x]));const result=this.materialize([...all.values()]);result.syncFormat=3;replaceState(result);this.record.known=[...all.values()];this.record.pending=[];this.record.snapshot=result;await this.persist();this.onStatus('已同步');return true;}catch(e){if(/(401|jwt expired|expired|invalid jwt)/i.test(e.message)&&await this.refresh()){this.running=false;return this.sync(getState,replaceState);}this.onStatus(`等待同步：${e.message}`);return false;}finally{this.running=false;}}
  }
  globalThis.CampSync=CampSync;
})();
